language: java
script: ant release
env: JRE7_HOME=/usr/lib/jvm/java-7-oracle/jre
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
sudo: required
before_script:
  - sudo apt-get install lib32z1 lib32ncurses5
