language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

addons:
  sonarqube: true

env:
  global:
    - secure: "G7EAJynuHaoIzSOAd8CoytF1R5dwHnATLAIdh/mmJr3SlBl5YLGHRoDdba109uL7MqTmDFpQjmpaEzMAglmDXgNU1RVBshH0hK24R4QseaJZ0ssXt5kFKu6H2UdYa+8jYggeWOKD+NeIsucHIBpXMlMzy+lUb+z+zu2jJsj4vQjRCiiUdM4gJaUftNudmVRlqvxR8yzre6eDFCUencjdjWPsQTujEk4f8LrTNory6MDfKAK0xrizrHsbTZs+a2Q0q5FadoOe8L7p9I75z1L/V5dHq/TCdjN/lnGjL180xM/7VuLl2r1soQRN2yyVKi0QombjEgRxHywlU8dAg9q0zIYuzq62pbHEW3b7cV45Db8RKrRZiIax7SzROcda46T1EJDjfMU0ASmR4Df5ICM91i4sb0T+fByjsCH9hf7KwKpuABL8BdeJjK2+5iBMCq4OpTTTbwHoQvAcJ0vphvEY3/jmBx3z37PWJFAp0ZJZO+n47k4l0a+/I5YGV7JXO8e2fSMtJ/7tCPjnLIZn/4yXX4Ok/Cp6aMPyO2dEAH6cTCNvY6jIg1lF8IgekXqkqKcEZEtkYvWIXT/YnBJnR2ytqRJwNckD1POwXFQNdUwZvK3huNQDU1B9Sb1MecDFbwEc2VXg0KJ1JxbZkVmKIQbO52zB61gFqhslSyOTv1BMH7o="
    - JRE7_HOME=/usr/lib/jvm/java-7-oracle/jre

sudo: required

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get -y --force-yes install lib32z1 lib32ncurses5 wine1.7

script:
  - ant all

after_success:
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then sonar-scanner -Dsonar.login=$SONAR_TOKEN; fi;
